In [1]:
#Importação de bibliotecas
import polars as pl

In [ ]:
# Leitura do arquivo e análise

In [16]:
df = pl.read_csv("/home/ulisses/Desafio_01_FTIA/Dados/dataset.csv")

In [17]:
display(df)

shape: (5_000, 11)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ idade ┆ estado ┆ escolarida ┆ renda_mens ┆ … ┆ prazo_mese ┆ finalidade ┆ dividas_at ┆ inadimplen │
│ ---   ┆ ---    ┆ de         ┆ al         ┆   ┆ s          ┆ ---        ┆ ivas       ┆ te         │
│ i64   ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ ---        ┆ ---        │
│       ┆        ┆ str        ┆ f64        ┆   ┆ i64        ┆            ┆ i64        ┆ i64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 52    ┆ MS     ┆ Ensino     ┆ 2911.82    ┆ … ┆ 60         ┆ Viagem     ┆ 1          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 49    ┆ RR     ┆ Ensino     ┆ 3176.43    ┆ … ┆ 24         ┆ Outros     ┆ 2          ┆ 0          │
│       ┆        ┆ Médio      ┆            ┆   ┆            ┆            ┆            ┆            │
│ 48    ┆ AL     ┆ Ensino     ┆ 3429.4     ┆ … ┆ 24         ┆ Outros     ┆ 5          ┆ 1          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 59    ┆ GO     ┆ Ensino Fun ┆ 10096.7    ┆ … ┆ 24         ┆ Reforma    ┆ 0          ┆ 0          │
│       ┆        ┆ damental   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 37    ┆ RJ     ┆ Ensino Fun ┆ 3033.25    ┆ … ┆ 6          ┆ Educação   ┆ 0          ┆ 1          │
│       ┆        ┆ damental   ┆            ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 31    ┆ PB     ┆ Ensino     ┆ 3374.04    ┆ … ┆ 24         ┆ Outros     ┆ 2          ┆ 0          │
│       ┆        ┆ Médio      ┆            ┆   ┆            ┆            ┆            ┆            │
│ 64    ┆ AM     ┆ Ensino     ┆ 3638.91    ┆ … ┆ 24         ┆ Reforma    ┆ 1          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 48    ┆ MT     ┆ Ensino     ┆ 2211.31    ┆ … ┆ 48         ┆ Saúde      ┆ 0          ┆ 1          │
│       ┆        ┆ Médio      ┆            ┆   ┆            ┆            ┆            ┆            │
│ 19    ┆ AP     ┆ Ensino     ┆ 14709.61   ┆ … ┆ 18         ┆ Veículo    ┆ 1          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 73    ┆ DF     ┆ Ensino     ┆ 19949.63   ┆ … ┆ 36         ┆ Outros     ┆ 1          ┆ 1          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [22]:
# Analisar a completude dos dados - Aparentemente todos os dados estão presentes
df_com = df.null_count()
display(df_com)

shape: (1, 11)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ idade ┆ estado ┆ escolarida ┆ renda_mens ┆ … ┆ prazo_mese ┆ finalidade ┆ dividas_at ┆ inadimplen │
│ ---   ┆ ---    ┆ de         ┆ al         ┆   ┆ s          ┆ ---        ┆ ivas       ┆ te         │
│ u32   ┆ u32    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ u32        ┆ ---        ┆ ---        │
│       ┆        ┆ u32        ┆ u32        ┆   ┆ u32        ┆            ┆ u32        ┆ u32        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 0      ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [24]:
# Análise de qualidade dos dados
df.describe()

shape: (9, 12)
┌────────────┬───────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ idade     ┆ estado ┆ escolarida ┆ … ┆ prazo_mes ┆ finalidad ┆ dividas_a ┆ inadimple │
│ ---        ┆ ---       ┆ ---    ┆ de         ┆   ┆ es        ┆ e         ┆ tivas     ┆ nte       │
│ str        ┆ f64       ┆ str    ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆        ┆ str        ┆   ┆ f64       ┆ str       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 5000.0    ┆ 5000   ┆ 5000       ┆ … ┆ 5000.0    ┆ 5000      ┆ 5000.0    ┆ 5000.0    │
│ null_count ┆ 0.0       ┆ 0      ┆ 0          ┆ … ┆ 0.0       ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 47.7674   ┆ null   ┆ null       ┆ … ┆ 29.922    ┆ null      ┆ 1.9004    ┆ 0.344     │
│ std        ┆ 31.646099 ┆ null   ┆ null       ┆ … ┆ 15.482515 ┆ null      ┆ 1.864719  ┆ 0.475089  │
│ min        ┆ 18.0      ┆   AC   ┆ Ensino Fun ┆ … ┆ 6.0       ┆ Educação  ┆ 0.0       ┆ 0.0       │
│            ┆           ┆        ┆ damental   ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 32.0      ┆ null   ┆ null       ┆ … ┆ 18.0      ┆ null      ┆ 0.0       ┆ 0.0       │
│ 50%        ┆ 46.0      ┆ null   ┆ null       ┆ … ┆ 24.0      ┆ null      ┆ 1.0       ┆ 0.0       │
│ 75%        ┆ 61.0      ┆ null   ┆ null       ┆ … ┆ 36.0      ┆ null      ┆ 3.0       ┆ 1.0       │
│ max        ┆ 750.0     ┆ TO     ┆ Pós-gradua ┆ … ┆ 60.0      ┆ Viagem    ┆ 7.0       ┆ 1.0       │
│            ┆           ┆        ┆ ção        ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
# Inconsistências:
## Idade máxima: 750 - Analisar outras idades que possam estar fora da realidade (abaixo de 18?) - Não possui.
## Tempo_emprego: max 74, identificar se está consistente com a idade (menor idade para contribuição é 14 anos - menor aprendiz)
## Score_credito: Verificar como funciona.No Brasil(Serasa) - o score vai de 0 a 1000. Apresenta aderência.

df_incons = df.filter(
# Identifica pessoas acima de 115 (pessoa mais idosa do Brasil)
    (pl.col("idade") > 115) |
# Verifica se o tempo de emprego é compatível com a idade
    (pl.col("idade") - pl.col("tempo_emprego_anos")   <= 14)
)
display(df_incons)
print(df_incons.count())

shape: (778, 11)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ idade ┆ estado ┆ escolarida ┆ renda_mens ┆ … ┆ prazo_mese ┆ finalidade ┆ dividas_at ┆ inadimplen │
│ ---   ┆ ---    ┆ de         ┆ al         ┆   ┆ s          ┆ ---        ┆ ivas       ┆ te         │
│ i64   ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ ---        ┆ ---        │
│       ┆        ┆ str        ┆ f64        ┆   ┆ i64        ┆            ┆ i64        ┆ i64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 37    ┆ RJ     ┆ Ensino Fun ┆ 3033.25    ┆ … ┆ 6          ┆ Educação   ┆ 0          ┆ 1          │
│       ┆        ┆ damental   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 22    ┆ CE     ┆ Ensino     ┆ 2571.1     ┆ … ┆ 24         ┆ Educação   ┆ 0          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 19    ┆ GO     ┆ Ensino     ┆ 5212.21    ┆ … ┆ 60         ┆ Outros     ┆ 2          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 20    ┆ MA     ┆ Ensino     ┆ 4557.43    ┆ … ┆ 48         ┆ Saúde      ┆ 2          ┆ 0          │
│       ┆        ┆ Médio      ┆            ┆   ┆            ┆            ┆            ┆            │
│ 32    ┆ AC     ┆ Ensino     ┆ 3843.02    ┆ … ┆ 12         ┆ Educação   ┆ 0          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 22    ┆ ES     ┆ Pós-gradua ┆ 6896.04    ┆ … ┆ 12         ┆ Reforma    ┆ 1          ┆ 0          │
│       ┆        ┆ ção        ┆            ┆   ┆            ┆            ┆            ┆            │
│ 34    ┆ SC     ┆ Pós-gradua ┆ 2640.66    ┆ … ┆ 60         ┆ Reforma    ┆ 1          ┆ 0          │
│       ┆        ┆ ção        ┆            ┆   ┆            ┆            ┆            ┆            │
│ 29    ┆ DF     ┆ Ensino     ┆ 3200.64    ┆ … ┆ 6          ┆ Veículo    ┆ 0          ┆ 1          │
│       ┆        ┆ Médio      ┆            ┆   ┆            ┆            ┆            ┆            │
│ 28    ┆ MG     ┆ Ensino     ┆ 2756.14    ┆ … ┆ 24         ┆ Outros     ┆ 3          ┆ 1          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
│ 18    ┆ PA     ┆ Ensino     ┆ 4794.26    ┆ … ┆ 36         ┆ Saúde      ┆ 7          ┆ 0          │
│       ┆        ┆ Superior   ┆            ┆   ┆            ┆            ┆            ┆            │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

shape: (1, 11)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ idade ┆ estado ┆ escolarida ┆ renda_mens ┆ … ┆ prazo_mese ┆ finalidade ┆ dividas_at ┆ inadimplen │
│ ---   ┆ ---    ┆ de         ┆ al         ┆   ┆ s          ┆ ---        ┆ ivas       ┆ te         │
│ u32   ┆ u32    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ u32        ┆ ---        ┆ ---        │
│       ┆        ┆ u32        ┆ u32        ┆   ┆ u32        ┆            ┆ u32        ┆ u32        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 778   ┆ 778    ┆ 778        ┆ 778        ┆ … ┆ 778        ┆ 778        ┆ 778        ┆ 778        │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [31]:
# Me ocorreu que os estados e a escolaridade (colunas texto) podem ter valores inválidos mesmo que não estejam nulos.
## Verificar:
print(df["estado"].unique())
print(df["escolaridade"].unique())
print(df["finalidade"].unique())

shape: (85,)
Series: 'estado' [str]
[
	"SC"
	"ES"
	"SE"
	"RR"
	" TO "
	…
	"  PB  "
	"  RS  "
	" PA "
	" RJ "
	"  RS "
]
shape: (4,)
Series: 'escolaridade' [str]
[
	"Ensino Superior"
	"Pós-graduação"
	"Ensino Médio"
	"Ensino Fundamental"
]
shape: (6,)
Series: 'finalidade' [str]
[
	"Saúde"
	"Educação"
	"Veículo"
	"Viagem"
	"Outros"
	"Reforma"
]

O retorno da lista única para Escolaridade e Finalidade não apresentam à primeira vista nenhuma inconsistência.

Escolaridade: "Ensino Superior", "Pós-graduação", "Ensino Médio", "Ensino Fundamental"
Finalidade: "Saúde", "Educação", "Veículo", "Viagem", "Outros", "Reforma"

In [41]:
# Ao realizar a analise de estados únicos recebi 85 possibilidades, inicialmente encontrei espaços na grafia das siglas.
## Vou realizar a limpeza antes de proceder com a análise
df = df.with_columns(
    pl.col("estado").str.strip_chars()
)

print(df["estado"].unique())

shape: (27,)
Series: 'estado' [str]
[
	"AP"
	"AL"
	"PE"
	"MT"
	"AM"
	…
	"RS"
	"RJ"
	"RR"
	"DF"
	"PR"
]

In [46]:
# A quantidade de siglas únicas agora está consistente com a quantidade de estados no Brasil - 27
df_estado = df["estado"].unique()
print(df_estado.count())

27

In [48]:
# verificando se apenas as siglas corretas foram utilizadas
estados_validos = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", 
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", 
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]
estados_invalidos = df.filter(
    ~pl.col("estado").is_in(estados_validos)
)

display(estados_invalidos)

shape: (0, 11)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ idade ┆ estado ┆ escolarida ┆ renda_mens ┆ … ┆ prazo_mese ┆ finalidade ┆ dividas_at ┆ inadimplen │
│ ---   ┆ ---    ┆ de         ┆ al         ┆   ┆ s          ┆ ---        ┆ ivas       ┆ te         │
│ i64   ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ ---        ┆ ---        │
│       ┆        ┆ str        ┆ f64        ┆   ┆ i64        ┆            ┆ i64        ┆ i64        │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

O retorno vazio do df acima significa que as siglas estão de acordo com as siglas corretas.

Análise para correção das inconsitências encontradas para idade e tempo_emprego_anos

- Idade acima de 115 (considerando a idade da pessoa mais idosa do Brasil)
- Pessoas com tempo de emprego incompátivel com a idade. Atualmente no Brasil idade mínima para assinatura da carteira é 14 anos (Menor aprendiz).